show_help() {
    echo -e "${YELLOW}Usage:${NC} ./install.sh [options]"
    echo ""
    echo -e "${GREEN}Options:${NC}"
    echo -e "  ${CYAN}-d, --dry-run${NC}    Simulation mode. For those with trust issues (rightfully so)."
    echo "                   Shows exactly what would happen without touching your disk."
    echo ""
    echo -e "  ${CYAN}-r, --restore${NC}    The \"Panic Button\". Reverts links and restores .bak files."
    echo "                   Digital duct tape for your configurations."
    echo ""
    echo -e "  ${CYAN}-h, --help${NC}       Shows this masterpiece of a help screen."
    echo ""
    echo -e "${GREEN}Examples:${NC}"
    echo "  ./install.sh -d          # Safe testing (Highly recommended)"
    echo "  ./install.sh             # The full send. Installs and auto-detects packages."
    echo "  ./install.sh -r          # Reverts symlinks and brings back your old configs."
    echo ""
    echo -e "${YELLOW}Note:${NC} This script uses GNU Stow. If you're on Arch/CachyOS, I'll handle the"
    echo "      dirty work. Otherwise, you're on your own, traveler."
}
    echo ""
    echo -e "${GREEN}Options:${NC}"
    echo -e "  ${CYAN}-d, --dry-run${NC}    Simulation mode. For those with trust issues (rightfully so)."
    echo "                   Shows exactly what would happen without touching your disk."
    echo ""
    echo -e "  ${CYAN}-r, --restore${NC}    The \"Panic Button\". Reverts links and restores .bak files."
    echo "                   Digital duct tape for your configurations."
    echo ""
    echo -e "  ${CYAN}-h, --help${NC}       Shows this masterpiece of a help screen."
    echo ""
    echo -e "${GREEN}Examples:${NC}"
    echo "  ./install.sh -d          # Safe testing (Highly recommended)"
    echo "  ./install.sh             # The full send. Installs and auto-detects packages."
    echo "  ./install.sh -r          # Reverts symlinks and brings back your old configs."
    echo ""
    echo -e "${YELLOW}Note:${NC} This script uses GNU Stow. If you're on Arch/CachyOS, I'll handle the"
    echo "      dirty work. Otherwise, you're on your own, traveler."
}
